# Generated by Django 6.0.5 on 2026-06-13 13:31

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot', '0001_enable_pgvector'),
        ('results', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAGDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('job_summary', 'Job Summary')], default='job_summary', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rag_document', to='results.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
